-- MySQL Script generated by MySQL Workbench
-- Wed Jul 10 20:35:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DOC_DETECTOR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DOC_DETECTOR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DOC_DETECTOR` ;
USE `DOC_DETECTOR` ;

-- -----------------------------------------------------
-- Table `DOC_DETECTOR`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOC_DETECTOR`.`address` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Province` ENUM('South', 'North', 'West', 'East') NULL,
  `District` VARCHAR(45) NULL,
  `Sector` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOC_DETECTOR`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOC_DETECTOR`.`user` (
  `Email` VARCHAR(50) NULL,
  `Telephone` VARCHAR(10) NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `address_ID` INT NOT NULL,
  `Username` VARCHAR(100) NULL,
  `PhotoPath` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `PubID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_claimant_address1_idx` (`address_ID` ASC) VISIBLE,
  UNIQUE INDEX `Telephone_UNIQUE` (`Telephone` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_claimant_address1`
    FOREIGN KEY (`address_ID`)
    REFERENCES `DOC_DETECTOR`.`address` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOC_DETECTOR`.`posted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOC_DETECTOR`.`posted` (
  `DocNum` VARCHAR(45) NOT NULL,
  `DocType` VARCHAR(45) NOT NULL DEFAULT 'NID',
  `PhotoPath` VARCHAR(45) NULL,
  `OwnersName` VARCHAR(45) NOT NULL,
  `user_ID` INT NOT NULL,
  `PostedAt` DATE NOT NULL,
  PRIMARY KEY (`DocNum`),
  INDEX `fk_posted_user1_idx` (`user_ID` ASC) VISIBLE,
  CONSTRAINT `fk_posted_user1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `DOC_DETECTOR`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOC_DETECTOR`.`claimed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOC_DETECTOR`.`claimed` (
  `DocNum` VARCHAR(45) NOT NULL,
  `DocType` VARCHAR(45) NOT NULL DEFAULT 'NID',
  `OwnersName` VARCHAR(100) NOT NULL,
  `user_ID` INT NOT NULL,
  `ClaimedAt` DATE NOT NULL,
  PRIMARY KEY (`DocNum`),
  INDEX `fk_claimed_user1_idx` (`user_ID` ASC) VISIBLE,
  CONSTRAINT `fk_claimed_user1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `DOC_DETECTOR`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
